ISPyB mock: drop ldapconnection object
The LdapLogin hwobj have been removed from mxcubecore,
see commit 4d877c07fec5dadecff726cf7f477898b3e788bf.

Remove the 'ldapconnection' hwobj that tries to instantiate that class.

This fixes following error message when starting MxCube using mock objects:

ERROR:HWR:Cannot parse Hardware Repository file /ldapconnection
Traceback (most recent call last):
  File "/home/elmjag/mxcube/core/mxcubecore/HardwareRepository.py", line 545, in parse_xml
    hardware_obj = HardwareObjectFileParser.parse_string(xml_string, ho_name)
  File "/home/elmjag/mxcube/core/mxcubecore/HardwareObjectFileParser.py", line 78, in parse_string
    xml.sax.parseString(str.encode(xml_hardware_object), cur_handler)
  File "/opt/micromamba/envs/mxcubeweb/lib/python3.10/xml/sax/__init__.py", line 48, in parseString
    parser.parse(inpsrc)
  File "/opt/micromamba/envs/mxcubeweb/lib/python3.10/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/opt/micromamba/envs/mxcubeweb/lib/python3.10/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/opt/micromamba/envs/mxcubeweb/lib/python3.10/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "/home/conda/feedstock_root/build_artifacts/python-split_1703344859861/work/Modules/pyexpat.c", line 416, in StartElement
  File "/opt/micromamba/envs/mxcubeweb/lib/python3.10/xml/sax/expatreader.py", line 333, in start_element
    self._cont_handler.startElement(name, AttributesImpl(attrs))
  File "/home/elmjag/mxcube/core/mxcubecore/HardwareObjectFileParser.py", line 276, in startElement
    new_object = instanciate_class(module_name, class_name, object_name)
  File "/home/elmjag/mxcube/core/mxcubecore/HardwareObjectFileParser.py", line 105, in instanciate_class
    module = load_module(module_name)
  File "/home/elmjag/mxcube/core/mxcubecore/HardwareObjectFileParser.py", line 91, in load_module
    return __import__(hardware_object_name, globals(), locals(), [""])
ModuleNotFoundError: No module named 'LdapLogin'